spring:
  datasource:
    url: ${POSTGRES_PATH}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${MICROSOFT_AD_TENANT_ID}
        credential:
          client-id: ${MICROSOFT_AD_CLIENT_ID}
          client-secret: ${MICROSOFT_AD_CLIENT_SECRET}
        app-id-uri: ${MICROSOFT_AD_APP_ID_URI}
        application-type: web_application_and_resource_server
        authorization-clients:
          graph:
            authorization-grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer # See here: https://authguidance.com/azure-ad-troubleshooting/#getuserinfo
            scopes:
              - User.Read
              - User.ReadBasic.All
              - User.Read.All
              - People.Read
          graph-invitation:
            authorization-grant-type: client_credentials
            scopes:
              - .default
        session-stateless: true

cors:
  allowedOrigins: ${ALLOWED_ORIGINS}
